// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  rule: __t.string(),
  pointerHz: __t.f64().name("pointer_hz"),
  pointerBudget: __t.f64().name("pointer_budget"),
  pointerHzEffective: __t.f64().name("pointer_hz_effective"),
  tickHz: __t.u32().name("tick_hz"),
  gain: __t.f64(),
  damping: __t.f64(),
  maxSpeed: __t.f64().name("max_speed"),
  influenceCap: __t.f64().name("influence_cap"),
  quorumMin: __t.u32().name("quorum_min"),
  quorumFrac: __t.f64().name("quorum_frac"),
  quorumRadius: __t.f64().name("quorum_radius"),
  quorumWindowMs: __t.u32().name("quorum_window_ms"),
  maxPlayers: __t.u32().name("max_players"),
  freshMs: __t.u32().name("fresh_ms"),
  dictatorSecs: __t.f64().name("dictator_secs"),
  autoAdvance: __t.bool().name("auto_advance"),
  paused: __t.bool(),
});
