// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  x: __t.f64(),
  y: __t.f64(),
  vx: __t.f64(),
  vy: __t.f64(),
  tx: __t.f64(),
  ty: __t.f64(),
  chaos: __t.f64(),
  active: __t.u32(),
  tick: __t.u64(),
  lastTickAt: __t.timestamp().name("last_tick_at"),
  dictator: __t.string(),
  dictatorUntil: __t.timestamp().name("dictator_until"),
});
