// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  kind: __t.string(),
  state: __t.string(),
  params: __t.string(),
  progress: __t.string(),
  startedAt: __t.timestamp().name("started_at"),
  deadline: __t.timestamp(),
  endedAt: __t.option(__t.timestamp()).name("ended_at"),
  score: __t.i32(),
  chaosSum: __t.f64().name("chaos_sum"),
  ticks: __t.u32(),
});
