// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  code: __t.string(),
  name: __t.string(),
  host: __t.identity(),
  players: __t.u32(),
  pointerHzEffective: __t.f64().name("pointer_hz_effective"),
  levelId: __t.u64().name("level_id"),
  createdAt: __t.timestamp().name("created_at"),
  lastActiveAt: __t.timestamp().name("last_active_at"),
});
