// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Admin = __t.object("Admin", {
  identity: __t.identity(),
  grantedAt: __t.timestamp(),
});
export type Admin = __Infer<typeof Admin>;

export const AdminFlag = __t.object("AdminFlag", {
  yes: __t.bool(),
});
export type AdminFlag = __Infer<typeof AdminFlag>;

export const AdminSecret = __t.object("AdminSecret", {
  id: __t.u32(),
  salt: __t.string(),
  hash: __t.string(),
});
export type AdminSecret = __Infer<typeof AdminSecret>;

export const AdvanceSchedule = __t.object("AdvanceSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  roomId: __t.u32(),
  afterLevelId: __t.u64(),
});
export type AdvanceSchedule = __Infer<typeof AdvanceSchedule>;

export const AmIAdmin = __t.object("AmIAdmin", {});
export type AmIAdmin = __Infer<typeof AmIAdmin>;

export const Award = __t.object("Award", {
  id: __t.u64(),
  roomId: __t.u32(),
  levelId: __t.u64(),
  title: __t.string(),
  who: __t.string(),
  name: __t.string(),
  detail: __t.string(),
});
export type Award = __Infer<typeof Award>;

export const Banned = __t.object("Banned", {
  identity: __t.identity(),
  until: __t.timestamp(),
});
export type Banned = __Infer<typeof Banned>;

export const Commentary = __t.object("Commentary", {
  id: __t.u64(),
  roomId: __t.u32(),
  at: __t.timestamp(),
  levelId: __t.u64(),
  text: __t.string(),
});
export type Commentary = __Infer<typeof Commentary>;

export const Config = __t.object("Config", {
  id: __t.u32(),
  rule: __t.string(),
  pointerHz: __t.f64(),
  pointerBudget: __t.f64(),
  tickHz: __t.u32(),
  gain: __t.f64(),
  damping: __t.f64(),
  maxSpeed: __t.f64(),
  influenceCap: __t.f64(),
  maxPlayers: __t.u32(),
  maxRooms: __t.u32(),
  freshMs: __t.u32(),
  dictatorSecs: __t.f64(),
  autoAdvance: __t.bool(),
  paused: __t.bool(),
});
export type Config = __Infer<typeof Config>;

export const Cursor = __t.object("Cursor", {
  id: __t.u32(),
  x: __t.f64(),
  y: __t.f64(),
  vx: __t.f64(),
  vy: __t.f64(),
  tx: __t.f64(),
  ty: __t.f64(),
  chaos: __t.f64(),
  active: __t.u32(),
  tick: __t.u64(),
  lastTickAt: __t.timestamp(),
  dictator: __t.string(),
  dictatorUntil: __t.timestamp(),
});
export type Cursor = __Infer<typeof Cursor>;

export const EventLog = __t.object("EventLog", {
  id: __t.u64(),
  roomId: __t.u32(),
  at: __t.timestamp(),
  kind: __t.string(),
  levelId: __t.u64(),
  who: __t.string(),
  payload: __t.string(),
});
export type EventLog = __Infer<typeof EventLog>;

export const Fx = __t.object("Fx", {
  roomId: __t.u32(),
  kind: __t.string(),
  x: __t.f64(),
  y: __t.f64(),
  who: __t.string(),
});
export type Fx = __Infer<typeof Fx>;

export const GhostFrame = __t.object("GhostFrame", {
  id: __t.u32(),
  data: __t.byteArray(),
});
export type GhostFrame = __Infer<typeof GhostFrame>;

export const Idle = __t.object("Idle", {
  identity: __t.identity(),
  since: __t.timestamp(),
});
export type Idle = __Infer<typeof Idle>;

export const Level = __t.object("Level", {
  id: __t.u64(),
  roomId: __t.u32(),
  kind: __t.string(),
  state: __t.string(),
  params: __t.string(),
  progress: __t.string(),
  startedAt: __t.timestamp(),
  deadline: __t.timestamp(),
  endedAt: __t.option(__t.timestamp()),
  score: __t.i32(),
  chaosSum: __t.f64(),
  ticks: __t.u32(),
});
export type Level = __Infer<typeof Level>;

export const LevelSecret = __t.object("LevelSecret", {
  levelId: __t.u64(),
  data: __t.string(),
});
export type LevelSecret = __Infer<typeof LevelSecret>;

export const ModeSettings = __t.object("ModeSettings", {
  kind: __t.string(),
  json: __t.string(),
  updatedAt: __t.timestamp(),
});
export type ModeSettings = __Infer<typeof ModeSettings>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  roomId: __t.u32(),
  name: __t.string(),
  color: __t.string(),
  team: __t.u8(),
  score: __t.i32(),
  connected: __t.bool(),
  joinedAt: __t.timestamp(),
});
export type Player = __Infer<typeof Player>;

export const PlayerStats = __t.object("PlayerStats", {
  identity: __t.identity(),
  roomId: __t.u32(),
  samples: __t.u32(),
  activeSamples: __t.u32(),
  agree: __t.u32(),
  disagree: __t.u32(),
  distSum: __t.f64(),
  activitySum: __t.f64(),
});
export type PlayerStats = __Infer<typeof PlayerStats>;

export const Pointer = __t.object("Pointer", {
  identity: __t.identity(),
  roomId: __t.u32(),
  x: __t.f32(),
  y: __t.f32(),
  activity: __t.f32(),
  updatedAt: __t.timestamp(),
});
export type Pointer = __Infer<typeof Pointer>;

export const PointerRate = __t.object("PointerRate", {
  identity: __t.identity(),
  tatUs: __t.u64(),
});
export type PointerRate = __Infer<typeof PointerRate>;

export const Room = __t.object("Room", {
  id: __t.u32(),
  code: __t.string(),
  name: __t.string(),
  host: __t.identity(),
  players: __t.u32(),
  pointerHzEffective: __t.f64(),
  levelId: __t.u64(),
  createdAt: __t.timestamp(),
  lastActiveAt: __t.timestamp(),
});
export type Room = __Infer<typeof Room>;

export const Session = __t.object("Session", {
  connectionId: __t.connectionId(),
  identity: __t.identity(),
});
export type Session = __Infer<typeof Session>;

export const TickSchedule = __t.object("TickSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type TickSchedule = __Infer<typeof TickSchedule>;

