// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AdminClaimReducer from "../admin_claim_reducer";
import AdminKickReducer from "../admin_kick_reducer";
import AdminResetRoundReducer from "../admin_reset_round_reducer";
import AdminSetConfigReducer from "../admin_set_config_reducer";
import AdminSetModeSettingsReducer from "../admin_set_mode_settings_reducer";
import AdminSetPassphraseReducer from "../admin_set_passphrase_reducer";
import AdminSetRuleReducer from "../admin_set_rule_reducer";
import AdminStartLevelReducer from "../admin_start_level_reducer";
import AdminStartStageReducer from "../admin_start_stage_reducer";
import AdminStopLevelReducer from "../admin_stop_level_reducer";
import CreateRoomReducer from "../create_room_reducer";
import JoinReducer from "../join_reducer";
import LeaveReducer from "../leave_reducer";
import PostCommentaryReducer from "../post_commentary_reducer";
import SetPointerReducer from "../set_pointer_reducer";

export type AdminClaimParams = __Infer<typeof AdminClaimReducer>;
export type AdminKickParams = __Infer<typeof AdminKickReducer>;
export type AdminResetRoundParams = __Infer<typeof AdminResetRoundReducer>;
export type AdminSetConfigParams = __Infer<typeof AdminSetConfigReducer>;
export type AdminSetModeSettingsParams = __Infer<typeof AdminSetModeSettingsReducer>;
export type AdminSetPassphraseParams = __Infer<typeof AdminSetPassphraseReducer>;
export type AdminSetRuleParams = __Infer<typeof AdminSetRuleReducer>;
export type AdminStartLevelParams = __Infer<typeof AdminStartLevelReducer>;
export type AdminStartStageParams = __Infer<typeof AdminStartStageReducer>;
export type AdminStopLevelParams = __Infer<typeof AdminStopLevelReducer>;
export type CreateRoomParams = __Infer<typeof CreateRoomReducer>;
export type JoinParams = __Infer<typeof JoinReducer>;
export type LeaveParams = __Infer<typeof LeaveReducer>;
export type PostCommentaryParams = __Infer<typeof PostCommentaryReducer>;
export type SetPointerParams = __Infer<typeof SetPointerReducer>;

